apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: v1beta2-demo
  title: Test Action template
  description: scaffolder v1beta2 template demo
spec:
  steps:
    - id: fetch-base # A unique id for the step
      name: Fetch Base # A title displayed in the frontend
      action: fetch:cookiecutter # an action to call
      input: # input that is passed as arguments to the action handler
        url: ./template
        values:
          name: '{{ parameters.name }}'
  owner: backstage/techdocs-core
  type: service
  parameters:
    - title: A registration form
      description: A simple form example.
      type: object
      required:
        - firstName
        - lastName
      properties:
        firstName:
          type: string
          title: First name
          default: Chuck
          ui:autofocus: true
          ui:emptyValue: ''
          ui:autocomplete: family-name
        lastName:
          type: string
          title: Last name
          ui:emptyValue: ''
          ui:autocomplete: given-name
        telephone:
          type: string
          title: Telephone
          minLength: 10
          ui:options:
            inputType: tel