# Notice the v1beta2 version
apiVersion: backstage.io/v1beta2
kind: Template
# some metadata about the template itself
metadata:
  name: e.dev
  title: e.dev host
  description: creates an *.e.dev 
spec:
  owner: backstage/techdocs-core
  type: Resource

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Domain Name
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: a unique name to launch your api => example.ethio.dev
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group